const VESMIRNE_OBJEKTY = [
  { id: "merkur", nazev: "Merkur", img: "https://t4.ftcdn.net/jpg/00/03/00/77/360_F_3007712_pD6pCDjczibyqjbyMsbzrjcU0j7qib.jpg", kategorie: "planeta", velikost: "4 879 km (průměr)", vzdalenost: "77–222 milionů km od Země", info: "Nejmenší planeta sluneční soustavy a nejbližší ke Slunci. Nemá atmosféru ani měsíce." },
  { id: "venus", nazev: "Venuše", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHoI5ibWLYRyptkTx4lEsXWysfvOBqUM66ew&s", kategorie: "planeta", velikost: "12 104 km (průměr)", vzdalenost: "38–261 milionů km od Země", info: "Nejžhavější planeta soustavy (465 °C). Hustá atmosféra z CO₂. Otáčí se pomalu pozpátku." },
  { id: "mars", nazev: "Mars", img: "https://static.scientificamerican.com/sciam/cache/file/C454F5A6-536E-4C9F-AA6AF354BB85A85B_source.jpg?w=900", kategorie: "planeta", velikost: "6 779 km (průměr)", vzdalenost: "54–401 milionů km od Země", info: "Červená planeta. Má nejvyšší sopku v soustavě – Olympus Mons (22 km). Možná budoucí domov lidí." },
  { id: "jupiter", nazev: "Jupiter", img: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Jupiter.jpg", kategorie: "planeta", velikost: "139 820 km (průměr)", vzdalenost: "~628–928 milionů km od Země", info: "Největší planeta sluneční soustavy. Bouře Velká červená skvrna trvá přes 350 let. Má 95 měsíců." },
  { id: "saturn", nazev: "Saturn", img: "https://www.aldebaran.cz/astrofyzika/sunsystem/saturn/Saturn_with_auroras.jpg", kategorie: "planeta", velikost: "116 460 km (průměr)", vzdalenost: "~1,2–1,67 miliardy km od Země", info: "Planeta s nádhernými prstenci z ledu a hornin. Je tak lehký, že by plaval na vodě." },
  { id: "uran", nazev: "Uran", img: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Uranus_as_seen_by_NASA%27s_Voyager_2_%28remastered%29_-_JPEG_converted.jpg", kategorie: "planeta", velikost: "50 724 km (průměr)", vzdalenost: "~2,6–3,15 miliardy km od Země", info: "Ledový obr. Otáčí se na boku – osa rotace je skloněna o 98°. Má 27 měsíců." },
  { id: "neptun", nazev: "Neptun", img: "https://www.aldebaran.cz/astrofyzika/sunsystem/neptun/Neptune.jpg", kategorie: "planeta", velikost: "49 244 km (průměr)", vzdalenost: "~4,3–4,7 miliardy km od Země", info: "Nejsevernější planeta. Větry dosahují 2 100 km/h – nejsilnější v soustavě." },
  { id: "slunce", nazev: "Slunce", img: "https://upload.wikimedia.org/wikipedia/commons/2/25/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819-02.jpg", kategorie: "hvezda", velikost: "1 392 700 km (průměr)", vzdalenost: "~149 milionů km od Země", info: "Naše hvězda. Tvoří 99,86 % hmoty celé sluneční soustavy. Povrch má teplotu ~5 500 °C." },
  { id: "sirius", nazev: "Sirius", img: "https://www.star-facts.com/wp-content/uploads/2019/09/Sirius-star.webp", kategorie: "hvezda", velikost: "~1,7 milionu km (průměr)", vzdalenost: "8,6 světelných let", info: "Nejjasnější hvězda noční oblohy. Je dvakrát větší než Slunce a 25× jasnější." },
  { id: "betelgeuse", nazev: "Betelgeuse", img: "https://media.cnn.com/api/v1/images/stellar/prod/betelgeuse-01.jpg?c=original", kategorie: "hvezda", velikost: "~1 miliarda km (průměr)", vzdalenost: "~700 světelných let", info: "Obří červený supergigant. Kdyby nahradil Slunce, pohltil by až k Jupiteru. Brzy exploduje jako supernova." },
  { id: "sagitarius", nazev: "Sagittarius A*", img: "https://www.azoquantum.com/images/Article_Images/ImageForArticle_589_17422208955759266.jpg", kategorie: "cerna-dira", velikost: "~44 milionů km (průměr)", vzdalenost: "~26 000 světelných let", info: "Supermasivní černá díra ve středu naší Galaxie. Hmotnost: 4 miliony Sluncí." },
  { id: "m87", nazev: "M87*", img: "https://miro.medium.com/1*eJTOgbeNN4CqtJrNmfrxag.jpeg", kategorie: "cerna-dira", velikost: "~120 miliard km (průměr)", vzdalenost: "~55 milionů světelných let", info: "První černá díra, která byla vyfotografována (2019). Hmotnost 6,5 miliardy Sluncí." },
  { id: "mesic", nazev: "Měsíc", img: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Full_Moon_Luc_Viatour.jpg", kategorie: "jine", velikost: "3 474 km (průměr)", vzdalenost: "~384 000 km od Země", info: "Jediný přirozený satelit Země. Lidé na něj přistáli v roce 1969 (Apollo 11). Způsobuje přílivy." },
  { id: "halley", nazev: "Halleyova kometa", img: "https://www.stoplusjednicka.cz/sites/default/files/clankyold/obrazky/1/4/9/8/3/4/1/6/0/0/halley_s_comet.jpg", kategorie: "jine", velikost: "~15 km (jádro)", vzdalenost: "Aktuálně za Neptunem", info: "Nejznámější kometa, viditelná ze Země každých 75–76 let. Naposledy v roce 1986, příště ~2061." },
  { id: "mlecna-draha", nazev: "Mléčná dráha", img: "https://www.irozhlas.cz/sites/default/files/styles/zpravy_fotogalerie_large/public/uploader/7b1616f72604eca92deb_210623-071019_ako.jpg?itok=VZO5KDwZ", kategorie: "jine", velikost: "~100 000 světelných let", vzdalenost: "Jsme uvnitř ní", info: "Naše galaxie. Obsahuje 200–400 miliard hvězd. Slunce ji obíhá jednou za ~225 milionů let." },
  { id: "andromeda", nazev: "Galaxie Andromeda", img: "https://edu.ceskatelevize.cz/storage/video/1200/6968-galaxie-a-andromeda.jpg", kategorie: "jine", velikost: "~220 000 světelných let", vzdalenost: "~2,5 milionu světelných let", info: "Nejbližší velká galaxie k Mléčné dráze. Za ~4,5 miliardy let se s ní srazí a splynou." }
];